# Generated by Django 4.2.6 on 2024-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpPesquisaOperacionalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desabrigado',
            name='abrigo',
        ),
        migrations.RemoveField(
            model_name='desabrigado',
            name='localizacao_atual',
        ),
        migrations.AddField(
            model_name='desabrigado',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desabrigado',
            name='sexo',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
